### ISSUE TITLE
[BUG] Text paraphrasing

### ISSUE THREAD

**Issue by NoB0** [ConvLab/ConvLab-3#185]
**Describe the bug**
Missing module `convlab.nlg.scgpt.utils` for SC-GPT.

**To Reproduce**
1. Run the following command: `python -m convlab.laug.Text_Paraphrasing.Text_Paraphrasing`

**Expected behavior**
Should print the paraphrased text and new span information.

**Actual behavior**
Return a `ModuleNotFoundError`:

```
convlab/laug/Word_Perturbation/multiwoz/task_oriented_eda.py:417: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  words = [word for word in words if word is not ""]
Traceback (most recent call last):
  File "/home/stud/nbernard/miniconda3/envs/sigir24/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/stud/nbernard/miniconda3/envs/sigir24/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "convlab/laug/__init__.py", line 2, in <module>
    from convlab.laug.Text_Paraphrasing.Text_Paraphrasing import Text_Paraphrasing
  File "convlab/laug/Text_Paraphrasing/Text_Paraphrasing.py", line 2, in <module>
    from convlab.nlg.scgpt.multiwoz.scgpt import SCGPT
  File "convlab/nlg/scgpt/multiwoz/scgpt.py", line 8, in <module>
    from convlab.nlg.scgpt.utils import tuple2seq
ModuleNotFoundError: No module named 'convlab.nlg.scgpt.utils'
```

**Additional context**

**Comment by zqwerty** [comment]
Sorry for the late reply! This problem comes from the mitigation from convlab-2 to convlab-3. Sorry for the inconvient. If you want to use LAUG, please try [convlab-2](https://github.com/thu-coai/Convlab-2) or the [official repo](https://github.com/thu-coai/LAUG) (recommended)
